export const SET_STATE = 'SET_STATE'
export const SET_THEME = 'SET_THEME'

// global moudle
export const global = {
  SET_GLOBAL_STATE: 'SET_GLOBAL_STATE',
  SET_LAYOUT: 'SET_LAYOUT',
  UNDO_LAYOUT: 'UNDO_LAYOUT',
  REDO_LAYOUT: 'REDO_LAYOUT',
  CHANGE_COLOR: 'CHANGE_COLOR',
  RESET_LAYOUT: 'RESET_LAYOUT',
  widget: {
    TOGGLE_SHOW_CARD: 'TOGGLE_SHOW_CARD'
  }
}
