export const SET_STATE = 'SET_STATE'
export const SET_LAYOUT = 'SET_LAYOUT'
export const UNDO_LAYOUT = 'UNDO_LAYOUT'
export const REDO_LAYOUT = 'REDO_LAYOUT'
export const CHANGE_COLOR = 'CHANGE_COLOR'
export const RESET_LAYOUT = 'RESET_LAYOUT'
